package com.greenlife.entity.enums;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_SHIPPING,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REVIEW_HIDDEN,
    WISHLIST_RESTOCK,
    SYSTEM_ANNOUNCEMENT,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_IN_PROGRESS,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED
}
